insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (4, 'Afghanistan', 'AF', 'AFG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (248, 'Aland Islands', 'AX', 'ALA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (8, 'Albania', 'AL', 'ALB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (12, 'Algeria', 'DZ', 'DZA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (16, 'American Samoa', 'AS', 'ASM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (20, 'Andorra', 'AD', 'AND')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (24, 'Angola', 'AO', 'AGO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (660, 'Anguilla', 'AI', 'AIA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (10, 'Antarctica', 'AQ', 'ATA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (28, 'Antigua and Barbuda', 'AG', 'ATG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (32, 'Argentina', 'AR', 'ARG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (51, 'Armenia', 'AM', 'ARM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (533, 'Aruba', 'AW', 'ABW')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (36, 'Australia', 'AU', 'AUS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (40, 'Austria', 'AT', 'AUT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (31, 'Azerbaijan', 'AZ', 'AZE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (44, 'Bahamas', 'BS', 'BHS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (48, 'Bahrain', 'BH', 'BHR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (50, 'Bangladesh', 'BD', 'BGD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (52, 'Barbados', 'BB', 'BRB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (112, 'Belarus', 'BY', 'BLR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (56, 'Belgium', 'BE', 'BEL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (84, 'Belize', 'BZ', 'BLZ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (204, 'Benin', 'BJ', 'BEN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (60, 'Bermuda', 'BM', 'BMU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (64, 'Bhutan', 'BT', 'BTN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (68, 'Plurinational State of Bolivia', 'BO', 'BOL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (535, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (70, 'Bosnia and Herzegovina', 'BA', 'BIH')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (72, 'Botswana', 'BW', 'BWA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (74, 'Bouvet Island', 'BV', 'BVT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (76, 'Brazil', 'BR', 'BRA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (86, 'British Indian Ocean Territory', 'IO', 'IOT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (96, 'Brunei Darussalam', 'BN', 'BRN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (100, 'Bulgaria', 'BG', 'BGR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (854, 'Burkina Faso', 'BF', 'BFA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (108, 'Burundi', 'BI', 'BDI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (116, 'Cambodia', 'KH', 'KHM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (120, 'Cameroon', 'CM', 'CMR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (124, 'Canada', 'CA', 'CAN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (132, 'Cape Verde', 'CV', 'CPV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (136, 'Cayman Islands', 'KY', 'CYM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (140, 'Central African Republic', 'CF', 'CAF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (148, 'Chad', 'TD', 'TCD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (152, 'Chile', 'CL', 'CHL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (156, 'China', 'CN', 'CHN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (162, 'Christmas Island', 'CX', 'CXR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (166, 'Cocos (Keeling) Islands', 'CC', 'CCK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (170, 'Colombia', 'CO', 'COL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (174, 'Comoros', 'KM', 'COM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (178, 'Congo', 'CG', 'COG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (180, 'The Democratic Republic of the Congo', 'CD', 'COD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (184, 'Cook Islands', 'CK', 'COK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (188, 'Costa Rica', 'CR', 'CRI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (384, 'Cote d''Ivoire', 'CI', 'CIV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (191, 'Croatia', 'HR', 'HRV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (192, 'Cuba', 'CU', 'CUB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (531, 'Curacao', 'CW', 'CUW')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (196, 'Cyprus', 'CY', 'CYP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (203, 'Czech Republic', 'CZ', 'CZE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (208, 'Denmark', 'DK', 'DNK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (262, 'Djibouti', 'DJ', 'DJI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (212, 'Dominica', 'DM', 'DMA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (214, 'Dominican Republic', 'DO', 'DOM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (218, 'Ecuador', 'EC', 'ECU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (818, 'Egypt', 'EG', 'EGY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (222, 'El Salvador', 'SV', 'SLV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (226, 'Equatorial Guinea', 'GQ', 'GNQ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (232, 'Eritrea', 'ER', 'ERI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (233, 'Estonia', 'EE', 'EST')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (231, 'Ethiopia', 'ET', 'ETH')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (238, 'Falkland Islands (Malvinas)', 'FK', 'FLK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (703, 'Faroe Islands', 'FO', '534')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (242, 'Fiji', 'FJ', 'FJI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (246, 'Finland', 'FI', 'FIN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (250, 'France', 'FR', 'FRA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (254, 'French Guiana', 'GF', 'GUF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (258, 'French Polynesia', 'PF', 'PYF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (260, 'French Southern Territories', 'TF', 'ATF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (266, 'Gabon', 'GA', 'GAB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (270, 'Gambia', 'GM', 'GMB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (268, 'Georgia', 'GE', 'GEO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (276, 'Germany', 'DE', 'DEU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (288, 'Ghana', 'GH', 'GHA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (292, 'Gibraltar', 'GI', 'GIB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (300, 'Greece', 'GR', 'GRC')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (304, 'Greenland', 'GL', 'GRL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (308, 'Grenada', 'GD', 'GRD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (312, 'Guadeloupe', 'GP', 'GLP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (316, 'Guam', 'GU', 'GUM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (320, 'Guatemala', 'GT', 'GTM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (831, 'Guernsey', 'GG', 'GGY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (324, 'Guinea', 'GN', 'GIN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (624, 'Guinea-Bissau', 'GW', 'GNB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (328, 'Guyana', 'GY', 'GUY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (332, 'Haiti', 'HT', 'HTI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (334, 'Heard Island and McDonald Islands', 'HM', 'HMD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (336, 'Holy See (Vatican City State)', 'VA', 'VAT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (340, 'Honduras', 'HN', 'HND')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (344, 'Hong Kong', 'HK', 'HKG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (348, 'Hungary', 'HU', 'HUN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (352, 'Iceland', 'IS', 'ISL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (356, 'India', 'IN', 'IND')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (360, 'Indonesia', 'ID', 'IDN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (364, 'Islamic Republic of Iran', 'IR', 'IRN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (368, 'Iraq', 'IQ', 'IRQ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (372, 'Ireland', 'IE', 'IRL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (833, 'Isle of Man', 'IM', 'IMN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (376, 'Israel', 'IL', 'ISR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (380, 'Italy', 'IT', 'ITA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (388, 'Jamaica', 'JM', 'JAM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (392, 'Japan', 'JP', 'JPN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (832, 'Jersey', 'JE', 'JEY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (400, 'Jordan', 'JO', 'JOR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (398, 'Kazakhstan', 'KZ', 'KAZ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (404, 'Kenya', 'KE', 'KEN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (296, 'Kiribati', 'KI', 'KIR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (408, 'Democratic People''s Republic of Korea', 'KP', 'PRK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (410, 'Republic of Korea', 'KR', 'KOR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (414, 'Kuwait', 'KW', 'KWT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (417, 'Kyrgyzstan', 'KG', 'KGZ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (418, 'Lao People''s Democratic Republic', 'LA', 'LAO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (428, 'Latvia', 'LV', 'LVA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (422, 'Lebanon', 'LB', 'LBN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (426, 'Lesotho', 'LS', 'LSO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (430, 'Liberia', 'LR', 'LBR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (434, 'Libyan Arab Jamahiriya', 'LY', 'LBY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (438, 'Liechtenstein', 'LI', 'LIE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (440, 'Lithuania', 'LT', 'LTU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (442, 'Luxembourg', 'LU', 'LUX')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (446, 'Macao', 'MO', 'MAC')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (807, 'The Former Yugoslav Republic of Macedonia', 'MK', 'MKD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (450, 'Madagascar', 'MG', 'MDG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (454, 'Malawi', 'MW', 'MWI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (458, 'Malaysia', 'MY', 'MYS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (462, 'Maldives', 'MV', 'MDV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (466, 'Mali', 'ML', 'MLI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (470, 'Malta', 'MT', 'MLT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (584, 'Marshall Islands', 'MH', 'MHL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (474, 'Martinique', 'MQ', 'MTQ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (478, 'Mauritania', 'MR', 'MRT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (480, 'Mauritius', 'MU', 'MUS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (175, 'Mayotte', 'YT', 'MYT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (484, 'Mexico', 'MX', 'MEX')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (583, 'Federated States of Micronesia', 'FM', 'FSM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (498, 'Republic of Moldova', 'MD', 'MDA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (492, 'Monaco', 'MC', 'MCO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (496, 'Mongolia', 'MN', 'MNG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (499, 'Montenegro', 'ME', 'MNE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (500, 'Montserrat', 'MS', 'MSR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (504, 'Morocco', 'MA', 'MAR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (508, 'Mozambique', 'MZ', 'MOZ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (104, 'Myanmar', 'MM', 'MMR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (516, 'Namibia', 'NA', 'NAM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (520, 'Nauru', 'NR', 'NRU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (524, 'Nepal', 'NP', 'NPL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (528, 'Netherlands', 'NL', 'NLD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (540, 'New Caledonia', 'NC', 'NCL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (554, 'New Zealand', 'NZ', 'NZL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (558, 'Nicaragua', 'NI', 'NIC')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (562, 'Niger', 'NE', 'NER')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (566, 'Nigeria', 'NG', 'NGA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (570, 'Niue', 'NU', 'NIU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (574, 'Norfolk Island', 'NF', 'NFK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (580, 'Northern Mariana Islands', 'MP', 'MNP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (578, 'Norway', 'NO', 'NOR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (275, 'Occupied Palestinian Territory', 'PS', 'PSE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (512, 'Oman', 'OM', 'OMN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (586, 'Pakistan', 'PK', 'PAK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (585, 'Palau', 'PW', 'PLW')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (591, 'Panama', 'PA', 'PAN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (598, 'Papua New Guinea', 'PG', 'PNG')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (600, 'Paraguay', 'PY', 'PRY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (604, 'Peru', 'PE', 'PER')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (608, 'Philippines', 'PH', 'PHL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (612, 'Pitcairn', 'PN', 'PCN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (616, 'Poland', 'PL', 'POL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (620, 'Portugal', 'PT', 'PRT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (630, 'Puerto Rico', 'PR', 'PRI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (634, 'Qatar', 'QA', 'QAT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (638, 'Reunion', 'RE', 'REU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (642, 'Romania', 'RO', 'ROU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (643, 'Russian Federation', 'RU', 'RUS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (646, 'Rwanda', 'RW', 'RWA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (703, 'Saint Barthelemy', 'BL', '534')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (654, 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (659, 'Saint Kitts and Nevis', 'KN', 'KNA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (662, 'Saint Lucia', 'LC', 'LCA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (663, 'Saint Martin (French part)', 'MF', 'MAF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (666, 'Saint Pierre and Miquelon', 'PM', 'SPM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (670, 'Saint Vincent and The Grenadines', 'VC', 'VCT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (882, 'Samoa', 'WS', 'WSM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (674, 'San Marino', 'SM', 'SMR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (678, 'Sao Tome and Principe', 'ST', 'STP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (682, 'Saudi Arabia', 'SA', 'SAU')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (686, 'Senegal', 'SN', 'SEN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (688, 'Serbia', 'RS', 'SRB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (690, 'Seychelles', 'SC', 'SYC')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (694, 'Sierra Leone', 'SL', 'SLE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (702, 'Singapore', 'SG', 'SGP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (534, 'Sint Maarten (Dutch part)', 'SX', 'SXM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (703, 'Slovakia', 'SK', 'SVK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (705, 'Slovenia', 'SI', 'SVN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (90, 'Solomon Islands', 'SB', 'SLB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (706, 'Somalia', 'SO', 'SOM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (710, 'South Africa', 'ZA', 'ZAF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (239, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (728, 'South Sudan', 'SS', 'SSD')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (724, 'Spain', 'ES', 'ESP')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (144, 'Sri Lanka', 'LK', 'LKA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (729, 'Sudan', 'SD', 'SDN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (740, 'Suriname', 'SR', 'SUR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (703, 'Svalbard and Jan Mayen', 'SJ', '534')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (748, 'Swaziland', 'SZ', 'SWZ')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (752, 'Sweden', 'SE', 'SWE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (756, 'Switzerland', 'CH', 'CHE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (760, 'Syrian Arab Republic', 'SY', 'SYR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (158, 'Taiwan, Province of China', 'TW', 'TWN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (762, 'Tajikistan', 'TJ', 'TJK')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (834, 'United Republic of Tanzania', 'TZ', 'TZA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (764, 'Thailand', 'TH', 'THA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (626, 'Timor-Leste', 'TL', 'TLS')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (768, 'Togo', 'TG', 'TGO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (772, 'Tokelau', 'TK', 'TKL')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (776, 'Tonga', 'TO', 'TON')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (780, 'Trinidad and Tobago', 'TT', 'TTO')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (788, 'Tunisia', 'TN', 'TUN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (792, 'Turkey', 'TR', 'TUR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (795, 'Turkmenistan', 'TM', 'TKM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (796, 'Turks and Caicos Islands', 'TC', 'TCA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (798, 'Tuvalu', 'TV', 'TUV')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (800, 'Uganda', 'UG', 'UGA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (804, 'Ukraine', 'UA', 'UKR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (784, 'United Arab Emirates', 'AE', 'ARE')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (826, 'United Kingdom', 'GB', 'GBR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (840, 'United States', 'US', 'USA')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (581, 'United States Minor Outlying Islands', 'UM', 'UMI')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (858, 'Uruguay', 'UY', 'URY')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (860, 'Uzbekistan', 'UZ', 'UZB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (548, 'Vanuatu', 'VU', 'VUT')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (862, 'Bolivarian Republic of Venezuela', 'VE', 'VEN')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (704, 'Viet Nam', 'VN', 'VNM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (92, 'British Virgin Islands', 'VG', 'VGB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (850, 'U.S. Virgin Islands', 'VI', 'VIR')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (876, 'Wallis and Futuna', 'WF', 'WLF')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (732, 'Western Sahara', 'EH', 'ESH')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (887, 'Yemen', 'YE', 'YEM')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (894, 'Zambia', 'ZM', 'ZMB')
insert iso_country_codes (country_iso_id, country_name, country_iso_alpha_2, country_iso_alpha_3) values (716, 'Zimbabwe', 'ZW', 'ZWE')
