insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (784,'AED','UAE Dirham')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (971,'AFN','Afghani')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (008,'ALL','Lek')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (051,'AMD','Armenian Dram')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (532,'ANG','Netherlands Antillean Guilder')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (973,'AOA','Kwanza')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (032,'ARS','Argentine Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (036,'AUD','Australian Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (533,'AWG','Aruban Florin')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (944,'AZN','Azerbaijanian Manat')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (977,'BAM','Convertible Mark')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (052,'BBD','Barbados Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (050,'BDT','Taka')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (975,'BGN','Bulgarian Lev')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (048,'BHD','Bahraini Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (108,'BIF','Burundi Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (060,'BMD','Bermudian Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (096,'BND','Brunei Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (068,'BOB','Boliviano')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (984,'BOV','Mvdol')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (986,'BRL','Brazilian Real')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (044,'BSD','Bahamian Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (064,'BTN','Ngultrum')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (072,'BWP','Pula')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (974,'BYR','Belarussian Ruble')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (084,'BZD','Belize Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (124,'CAD','Canadian Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (976,'CDF','Congolese Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (947,'CHE','WIR Euro')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (756,'CHF','Swiss Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (948,'CHW','WIR Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (990,'CLF','Unidad de Fomento')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (152,'CLP','Chilean Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (156,'CNY','Yuan Renminbi')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (170,'COP','Colombian Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (970,'COU','Unidad de Valor Real')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (188,'CRC','Costa Rican Colon')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (931,'CUC','Peso Convertible')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (192,'CUP','Cuban Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (132,'CVE','Cape Verde Escudo')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (203,'CZK','Czech Koruna')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (262,'DJF','Djibouti Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (208,'DKK','Danish Krone')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (214,'DOP','Dominican Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (012,'DZD','Algerian Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (818,'EGP','Egyptian Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (232,'ERN','Nakfa')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (230,'ETB','Ethiopian Birr')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (978,'EUR','Euro')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (242,'FJD','Fiji Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (238,'FKP','Falkland Islands Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (826,'GBP','Pound Sterling')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (981,'GEL','Lari')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (936,'GHS','Ghana Cedi')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (292,'GIP','Gibraltar Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (270,'GMD','Dalasi')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (324,'GNF','Guinea Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (320,'GTQ','Quetzal')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (328,'GYD','Guyana Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (344,'HKD','Hong Kong Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (340,'HNL','Lempira')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (191,'HRK','Croatian Kuna')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (332,'HTG','Gourde')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (348,'HUF','Forint')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (360,'IDR','Rupiah')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (376,'ILS','New Israeli Sheqel')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (356,'INR','Indian Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (368,'IQD','Iraqi Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (364,'IRR','Iranian Rial')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (352,'ISK','Iceland Krona')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (388,'JMD','Jamaican Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (400,'JOD','Jordanian Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (392,'JPY','Yen')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (404,'KES','Kenyan Shilling')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (417,'KGS','Som')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (116,'KHR','Riel')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (174,'KMF','Comoro Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (408,'KPW','North Korean Won')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (410,'KRW','Won')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (414,'KWD','Kuwaiti Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (136,'KYD','Cayman Islands Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (398,'KZT','Tenge')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (418,'LAK','Kip')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (422,'LBP','Lebanese Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (144,'LKR','Sri Lanka Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (430,'LRD','Liberian Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (426,'LSL','Loti')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (440,'LTL','Lithuanian Litas')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (428,'LVL','Latvian Lats')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (434,'LYD','Libyan Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (504,'MAD','Moroccan Dirham')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (498,'MDL','Moldovan Leu')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (969,'MGA','Malagasy Ariary')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (807,'MKD','Denar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (104,'MMK','Kyat')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (496,'MNT','Tugrik')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (446,'MOP','Pataca')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (478,'MRO','Ouguiya')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (480,'MUR','Mauritius Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (462,'MVR','Rufiyaa')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (454,'MWK','Kwacha')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (484,'MXN','Mexican Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (979,'MXV','Mexican Unidad de Inversion (UDI)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (458,'MYR','Malaysian Ringgit')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (943,'MZN','Mozambique Metical')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (516,'NAD','Namibia Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (566,'NGN','Naira')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (558,'NIO','Cordoba Oro')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (578,'NOK','Norwegian Krone')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (524,'NPR','Nepalese Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (554,'NZD','New Zealand Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (512,'OMR','Rial Omani')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (590,'PAB','Balboa')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (604,'PEN','Nuevo Sol')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (598,'PGK','Kina')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (608,'PHP','Philippine Peso')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (586,'PKR','Pakistan Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (985,'PLN','Zloty')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (600,'PYG','Guarani')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (634,'QAR','Qatari Rial')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (946,'RON','New Romanian Leu')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (941,'RSD','Serbian Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (643,'RUB','Russian Ruble')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (646,'RWF','Rwanda Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (682,'SAR','Saudi Riyal')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (090,'SBD','Solomon Islands Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (690,'SCR','Seychelles Rupee')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (938,'SDG','Sudanese Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (752,'SEK','Swedish Krona')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (702,'SGD','Singapore Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (654,'SHP','Saint Helena Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (694,'SLL','Leone')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (706,'SOS','Somali Shilling')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (968,'SRD','Surinam Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (728,'SSP','South Sudanese Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (678,'STD','Dobra')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (222,'SVC','El Salvador Colon')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (760,'SYP','Syrian Pound')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (748,'SZL','Lilangeni')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (764,'THB','Baht')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (972,'TJS','Somoni')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (934,'TMT','Turkmenistan New Manat')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (788,'TND','Tunisian Dinar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (776,'TOP','Pa’anga')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (949,'TRY','Turkish Lira')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (780,'TTD','Trinidad and Tobago Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (901,'TWD','New Taiwan Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (834,'TZS','Tanzanian Shilling')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (980,'UAH','Hryvnia')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (800,'UGX','Uganda Shilling')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (840,'USD','US Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (997,'USN','US Dollar (Next day)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (998,'USS','US Dollar (Same day)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (940,'UYI','Uruguay Peso en Unidades Indexadas (URUIURUI)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (858,'UYU','Peso Uruguayo')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (860,'UZS','Uzbekistan Sum')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (937,'VEF','Bolivar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (704,'VND','Dong')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (548,'VUV','Vatu')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (882,'WST','Tala')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (950,'XAF','CFA Franc BEAC')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (961,'XAG','Silver')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (959,'XAU','Gold')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (955,'XBA','Bond Markets Unit European Composite Unit (EURCO)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (956,'XBB','Bond Markets Unit European Monetary Unit (E.M.U.-6)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (957,'XBC','Bond Markets Unit European Unit of Account 9 (E.U.A.-9)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (958,'XBD','Bond Markets Unit European Unit of Account 17 (E.U.A.-17)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (951,'XCD','East Caribbean Dollar')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (960,'XDR','SDR (Special Drawing Right)')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (952,'XOF','CFA Franc BCEAO')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (964,'XPD','Palladium')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (953,'XPF','CFP Franc')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (962,'XPT','Platinum')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (994,'XSU','Sucre')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (963,'XTS','Codes specifically reserved for testing purposes')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (965,'XUA','ADB Unit of Account')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (999,'XXX','The codes assigned for transactions where no currency is involved')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (886,'YER','Yemeni Rial')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (710,'ZAR','Rand')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (967,'ZMW','Zambian Kwacha')
insert into iso_currency_codes(currency_iso_id, currency_code, currency_name) values (932,'ZWL','Zimbabwe Dollar')