insert into transaction_type_categories (transaction_type_category_id,debit_or_credit,name) values(1,'Credit','Payments')
insert into transaction_type_categories (transaction_type_category_id,debit_or_credit,name) values(2,'Credit','Other Credits')
insert into transaction_type_categories (transaction_type_category_id,debit_or_credit,name) values(3,'Debit','Purchases')
insert into transaction_type_categories (transaction_type_category_id,debit_or_credit,name) values(4,'Debit','Fees')

insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(10,1,'Purchase',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(11,1,'Credit Voucher',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(20,1,'Manual Cash Disbursement',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(22,1,'ATM Cash Disbursement',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(30,1,'Payment Reversal - NSF Check',1)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(31,1,'Payment',1)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(40,1,'Finance Charge',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(50,1,'Annual Fee',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(52,1,'Miscellaneous Fees',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(54,1,'NSF Check Fee',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(56,1,'Report Fee',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(61,1,'Credit Adjustment',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(62,1,'Debit Adjustment',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(63,1,'Finance Charge Credit Adjustment',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(64,1,'Finance Charge Debit Adjustment',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(65,1,'Other Credits',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(66,1,'Other Debits',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(71,1,'Fuel Discount',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(73,1,'Non-Fuel Discount',2)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(80,1,'Convenience Checks',3)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(82,1,'Convenience Checks Fees',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(84,1,'Travelers Checks Fees',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(86,1,'ATM Fees',4)
insert into transaction_types (transaction_type_id,card_scheme_id,name,transaction_type_category_id) values(88,1,'Late Fees',4)
