--fix incorrect country codes
UPDATE iso_country_codes SET country_iso_id = 298, country_iso_alpha_3 = 'FOR' WHERE country_iso_alpha_2 = 'FO'
UPDATE iso_country_codes SET country_iso_id = 590, country_iso_alpha_3 = 'BLM' WHERE country_iso_alpha_2 = 'BL'
UPDATE iso_country_codes SET country_iso_id = 744, country_iso_alpha_3 = 'SJM' WHERE country_iso_alpha_2 = 'SJ'
go
ALTER TABLE iso_country_codes ADD currency_iso_id int NULL FOREIGN KEY REFERENCES iso_currency_codes(currency_iso_id)
go
update iso_country_codes set currency_iso_id = 971 where country_iso_id = 4
update iso_country_codes set currency_iso_id = 8 where country_iso_id = 8
update iso_country_codes set currency_iso_id = 12 where country_iso_id = 12
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 16
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 20
update iso_country_codes set currency_iso_id = 973 where country_iso_id = 24
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 660
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 28
update iso_country_codes set currency_iso_id = 32 where country_iso_id = 32
update iso_country_codes set currency_iso_id = 51 where country_iso_id = 51
update iso_country_codes set currency_iso_id = 533 where country_iso_id = 533
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 36
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 40
update iso_country_codes set currency_iso_id = 944 where country_iso_id = 31
update iso_country_codes set currency_iso_id = 44 where country_iso_id = 44
update iso_country_codes set currency_iso_id = 48 where country_iso_id = 48
update iso_country_codes set currency_iso_id = 50 where country_iso_id = 50
update iso_country_codes set currency_iso_id = 52 where country_iso_id = 52
update iso_country_codes set currency_iso_id = 974 where country_iso_id = 112
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 56
update iso_country_codes set currency_iso_id = 84 where country_iso_id = 84
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 204
update iso_country_codes set currency_iso_id = 60 where country_iso_id = 60
update iso_country_codes set currency_iso_id = 356 where country_iso_id = 64
update iso_country_codes set currency_iso_id = 68 where country_iso_id = 68
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 535
update iso_country_codes set currency_iso_id = 977 where country_iso_id = 70
update iso_country_codes set currency_iso_id = 72 where country_iso_id = 72
update iso_country_codes set currency_iso_id = 578 where country_iso_id = 74
update iso_country_codes set currency_iso_id = 986 where country_iso_id = 76
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 86
update iso_country_codes set currency_iso_id = 96 where country_iso_id = 96
update iso_country_codes set currency_iso_id = 975 where country_iso_id = 100
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 854
update iso_country_codes set currency_iso_id = 108 where country_iso_id = 108
update iso_country_codes set currency_iso_id = 116 where country_iso_id = 116
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 120
update iso_country_codes set currency_iso_id = 124 where country_iso_id = 124
update iso_country_codes set currency_iso_id = 132 where country_iso_id = 132
update iso_country_codes set currency_iso_id = 136 where country_iso_id = 136
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 140
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 148
update iso_country_codes set currency_iso_id = 152 where country_iso_id = 152
update iso_country_codes set currency_iso_id = 156 where country_iso_id = 156
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 162
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 166
update iso_country_codes set currency_iso_id = 170 where country_iso_id = 170
update iso_country_codes set currency_iso_id = 174 where country_iso_id = 174
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 178
update iso_country_codes set currency_iso_id = 976 where country_iso_id = 180
update iso_country_codes set currency_iso_id = 554 where country_iso_id = 184
update iso_country_codes set currency_iso_id = 188 where country_iso_id = 188
update iso_country_codes set currency_iso_id = 191 where country_iso_id = 191
update iso_country_codes set currency_iso_id = 192 where country_iso_id = 192
update iso_country_codes set currency_iso_id = 532 where country_iso_id = 531
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 196
update iso_country_codes set currency_iso_id = 203 where country_iso_id = 203
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 384
update iso_country_codes set currency_iso_id = 208 where country_iso_id = 208
update iso_country_codes set currency_iso_id = 262 where country_iso_id = 262
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 212
update iso_country_codes set currency_iso_id = 214 where country_iso_id = 214
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 218
update iso_country_codes set currency_iso_id = 818 where country_iso_id = 818
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 222
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 226
update iso_country_codes set currency_iso_id = 232 where country_iso_id = 232
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 233
update iso_country_codes set currency_iso_id = 230 where country_iso_id = 231
update iso_country_codes set currency_iso_id = 238 where country_iso_id = 238
update iso_country_codes set currency_iso_id = 208 where country_iso_id = 234
update iso_country_codes set currency_iso_id = 242 where country_iso_id = 242
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 246
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 250
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 254
update iso_country_codes set currency_iso_id = 953 where country_iso_id = 258
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 260
update iso_country_codes set currency_iso_id = 950 where country_iso_id = 266
update iso_country_codes set currency_iso_id = 270 where country_iso_id = 270
update iso_country_codes set currency_iso_id = 981 where country_iso_id = 268
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 276
update iso_country_codes set currency_iso_id = 936 where country_iso_id = 288
update iso_country_codes set currency_iso_id = 292 where country_iso_id = 292
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 300
update iso_country_codes set currency_iso_id = 208 where country_iso_id = 304
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 308
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 312
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 316
update iso_country_codes set currency_iso_id = 320 where country_iso_id = 320
update iso_country_codes set currency_iso_id = 826 where country_iso_id = 831
update iso_country_codes set currency_iso_id = 324 where country_iso_id = 324
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 624
update iso_country_codes set currency_iso_id = 328 where country_iso_id = 328
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 332
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 334
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 336
update iso_country_codes set currency_iso_id = 340 where country_iso_id = 340
update iso_country_codes set currency_iso_id = 344 where country_iso_id = 344
update iso_country_codes set currency_iso_id = 348 where country_iso_id = 348
update iso_country_codes set currency_iso_id = 352 where country_iso_id = 352
update iso_country_codes set currency_iso_id = 356 where country_iso_id = 356
update iso_country_codes set currency_iso_id = 360 where country_iso_id = 360
update iso_country_codes set currency_iso_id = 364 where country_iso_id = 364
update iso_country_codes set currency_iso_id = 368 where country_iso_id = 368
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 372
update iso_country_codes set currency_iso_id = 826 where country_iso_id = 833
update iso_country_codes set currency_iso_id = 376 where country_iso_id = 376
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 380
update iso_country_codes set currency_iso_id = 388 where country_iso_id = 388
update iso_country_codes set currency_iso_id = 392 where country_iso_id = 392
update iso_country_codes set currency_iso_id = 826 where country_iso_id = 832
update iso_country_codes set currency_iso_id = 400 where country_iso_id = 400
update iso_country_codes set currency_iso_id = 398 where country_iso_id = 398
update iso_country_codes set currency_iso_id = 404 where country_iso_id = 404
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 296
update iso_country_codes set currency_iso_id = 408 where country_iso_id = 408
update iso_country_codes set currency_iso_id = 410 where country_iso_id = 410
update iso_country_codes set currency_iso_id = 414 where country_iso_id = 414
update iso_country_codes set currency_iso_id = 417 where country_iso_id = 417
update iso_country_codes set currency_iso_id = 418 where country_iso_id = 418
update iso_country_codes set currency_iso_id = 428 where country_iso_id = 428
update iso_country_codes set currency_iso_id = 422 where country_iso_id = 422
update iso_country_codes set currency_iso_id = 710 where country_iso_id = 426
update iso_country_codes set currency_iso_id = 430 where country_iso_id = 430
update iso_country_codes set currency_iso_id = 434 where country_iso_id = 434
update iso_country_codes set currency_iso_id = 756 where country_iso_id = 438
update iso_country_codes set currency_iso_id = 440 where country_iso_id = 440
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 442
update iso_country_codes set currency_iso_id = 446 where country_iso_id = 446
update iso_country_codes set currency_iso_id = 807 where country_iso_id = 807
update iso_country_codes set currency_iso_id = 969 where country_iso_id = 450
update iso_country_codes set currency_iso_id = 454 where country_iso_id = 454
update iso_country_codes set currency_iso_id = 458 where country_iso_id = 458
update iso_country_codes set currency_iso_id = 462 where country_iso_id = 462
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 466
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 470
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 584
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 474
update iso_country_codes set currency_iso_id = 478 where country_iso_id = 478
update iso_country_codes set currency_iso_id = 480 where country_iso_id = 480
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 175
update iso_country_codes set currency_iso_id = 484 where country_iso_id = 484
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 583
update iso_country_codes set currency_iso_id = 498 where country_iso_id = 498
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 492
update iso_country_codes set currency_iso_id = 496 where country_iso_id = 496
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 499
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 500
update iso_country_codes set currency_iso_id = 504 where country_iso_id = 504
update iso_country_codes set currency_iso_id = 943 where country_iso_id = 508
update iso_country_codes set currency_iso_id = 104 where country_iso_id = 104
update iso_country_codes set currency_iso_id = 710 where country_iso_id = 516
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 520
update iso_country_codes set currency_iso_id = 524 where country_iso_id = 524
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 528
update iso_country_codes set currency_iso_id = 953 where country_iso_id = 540
update iso_country_codes set currency_iso_id = 554 where country_iso_id = 554
update iso_country_codes set currency_iso_id = 558 where country_iso_id = 558
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 562
update iso_country_codes set currency_iso_id = 566 where country_iso_id = 566
update iso_country_codes set currency_iso_id = 554 where country_iso_id = 570
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 574
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 580
update iso_country_codes set currency_iso_id = 578 where country_iso_id = 578
update iso_country_codes set currency_iso_id = 512 where country_iso_id = 512
update iso_country_codes set currency_iso_id = 586 where country_iso_id = 586
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 585
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 591
update iso_country_codes set currency_iso_id = 598 where country_iso_id = 598
update iso_country_codes set currency_iso_id = 600 where country_iso_id = 600
update iso_country_codes set currency_iso_id = 604 where country_iso_id = 604
update iso_country_codes set currency_iso_id = 608 where country_iso_id = 608
update iso_country_codes set currency_iso_id = 554 where country_iso_id = 612
update iso_country_codes set currency_iso_id = 985 where country_iso_id = 616
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 620
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 630
update iso_country_codes set currency_iso_id = 634 where country_iso_id = 634
update iso_country_codes set currency_iso_id = 946 where country_iso_id = 642
update iso_country_codes set currency_iso_id = 643 where country_iso_id = 643
update iso_country_codes set currency_iso_id = 646 where country_iso_id = 646
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 638
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 652
update iso_country_codes set currency_iso_id = 654 where country_iso_id = 654
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 659
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 662
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 663
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 666
update iso_country_codes set currency_iso_id = 951 where country_iso_id = 670
update iso_country_codes set currency_iso_id = 882 where country_iso_id = 882
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 674
update iso_country_codes set currency_iso_id = 678 where country_iso_id = 678
update iso_country_codes set currency_iso_id = 682 where country_iso_id = 682
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 686
update iso_country_codes set currency_iso_id = 941 where country_iso_id = 688
update iso_country_codes set currency_iso_id = 690 where country_iso_id = 690
update iso_country_codes set currency_iso_id = 694 where country_iso_id = 694
update iso_country_codes set currency_iso_id = 702 where country_iso_id = 702
update iso_country_codes set currency_iso_id = 532 where country_iso_id = 534
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 703
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 705
update iso_country_codes set currency_iso_id = 90 where country_iso_id = 90
update iso_country_codes set currency_iso_id = 706 where country_iso_id = 706
update iso_country_codes set currency_iso_id = 710 where country_iso_id = 710
update iso_country_codes set currency_iso_id = 826 where country_iso_id = 239
update iso_country_codes set currency_iso_id = 728 where country_iso_id = 728
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 724
update iso_country_codes set currency_iso_id = 144 where country_iso_id = 144
update iso_country_codes set currency_iso_id = 938 where country_iso_id = 729
update iso_country_codes set currency_iso_id = 968 where country_iso_id = 740
update iso_country_codes set currency_iso_id = 578 where country_iso_id = 744
update iso_country_codes set currency_iso_id = 748 where country_iso_id = 748
update iso_country_codes set currency_iso_id = 752 where country_iso_id = 752
update iso_country_codes set currency_iso_id = 756 where country_iso_id = 756
update iso_country_codes set currency_iso_id = 760 where country_iso_id = 760
update iso_country_codes set currency_iso_id = 901 where country_iso_id = 158
update iso_country_codes set currency_iso_id = 972 where country_iso_id = 762
update iso_country_codes set currency_iso_id = 834 where country_iso_id = 834
update iso_country_codes set currency_iso_id = 764 where country_iso_id = 764
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 626
update iso_country_codes set currency_iso_id = 952 where country_iso_id = 768
update iso_country_codes set currency_iso_id = 554 where country_iso_id = 772
update iso_country_codes set currency_iso_id = 776 where country_iso_id = 776
update iso_country_codes set currency_iso_id = 780 where country_iso_id = 780
update iso_country_codes set currency_iso_id = 788 where country_iso_id = 788
update iso_country_codes set currency_iso_id = 949 where country_iso_id = 792
update iso_country_codes set currency_iso_id = 934 where country_iso_id = 795
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 796
update iso_country_codes set currency_iso_id = 36 where country_iso_id = 798
update iso_country_codes set currency_iso_id = 800 where country_iso_id = 800
update iso_country_codes set currency_iso_id = 980 where country_iso_id = 804
update iso_country_codes set currency_iso_id = 784 where country_iso_id = 784
update iso_country_codes set currency_iso_id = 826 where country_iso_id = 826
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 840
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 581
update iso_country_codes set currency_iso_id = 858 where country_iso_id = 858
update iso_country_codes set currency_iso_id = 860 where country_iso_id = 860
update iso_country_codes set currency_iso_id = 548 where country_iso_id = 548
update iso_country_codes set currency_iso_id = 937 where country_iso_id = 862
update iso_country_codes set currency_iso_id = 704 where country_iso_id = 704
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 92
update iso_country_codes set currency_iso_id = 840 where country_iso_id = 850
update iso_country_codes set currency_iso_id = 953 where country_iso_id = 876
update iso_country_codes set currency_iso_id = 504 where country_iso_id = 732
update iso_country_codes set currency_iso_id = 886 where country_iso_id = 887
update iso_country_codes set currency_iso_id = 967 where country_iso_id = 894
update iso_country_codes set currency_iso_id = 932 where country_iso_id = 716
update iso_country_codes set currency_iso_id = 978 where country_iso_id = 248
go
execute sp_rename 'iso_country_codes.currency_iso_id', 'currency_iso_number', 'COLUMN'
execute sp_rename 'iso_country_codes.country_iso_id', 'country_iso_number', 'COLUMN'
execute sp_rename 'iso_country_codes', 'countries'